// Generated by npm run generate:api-contract-types.
// Do not edit manually.

export interface Health {
  status: 'ok'
}

export interface Product {
  id: number
  title: string
  price: number
  category: string
  description: string
}

export interface CreatedProduct {
  id: number
  title: string
  price: number
}

export type ProductList = {
  id: number
  title: string
  price: number
  category: string
  description: string
}[]

export type Categories = string[]

export interface User {
  id: number
  name: string
  email: string
}

export type UserList = {
  id: number
  name: string
  email: string
}[]

export interface Token {
  token: string
}

export interface Post {
  id: number
  title: string
  body: string
  userId: number
}

export type PostList = {
  id: number
  title: string
  body: string
  userId: number
}[]

export interface UpdatedPost {
  id: number
  title: string
}

export interface EmptyObject {}

export interface ApiError {
  error: string
}
